name: smartpave
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - folium>=0.12.0
  - xgboost>=1.5.0
  - lightgbm>=3.2.0
  - joblib>=1.1.0
  - geopandas>=0.10.0
  - shapely>=1.8.0
  - pyproj>=3.3.0
  - statsmodels>=0.13.0
  - tqdm>=4.62.0
  - pyyaml>=6.0
  - jupyter>=1.0.0
  - ipywidgets>=7.6.0
  - pip
  - pip:
    - snowflake-connector-python>=2.7.0
    - snowflake-sqlalchemy>=1.3.0
